"""Add owner column to projects table

Revision ID: 37ea84715b32
Revises: d08176cbb4c2
Create Date: 2026-09-13 12:58:15.444444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ea84715b32'
down_revision: Union[str, Sequence[str], None] = 'd08176cbb4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'owner')
    # ### end Alembic commands ###
